language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls

deploy:
  provider: script
  script: docs/deploy.sh
  on:
    branch: feat/docs
    php: '7.1'
