language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - mkdir -p build/logs
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls
