language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls
  - pip install -r docs/requirements.txt;cd docs/php-form;mkdocs build
  - tar -zcvf phpform.tar.gz -C site .
  - curl -X POST -H "Content-Type: multipart/form-data" -H "Api-Key: $ALEXANDRIA_APIKEY" -F "archive=@phpform.tar.gz" https://alexandriadocs.io/api/v1/projects/upload/
